name: SalesOps CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build API
        working-directory: apps/api
        run: |
          npm install
          npm run build

      - name: Build Dashboard
        working-directory: apps/web/dashboard
        run: |
          npm install
          npm run build

      - name: Build Docker Images
        run: docker compose build